name: Swift

on: 
  push: 


jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: | 
        pod deintegrate
        pod install
        pod update
        xcodebuild clean -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS"
        xcodebuild build -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS" -UseModernBuildSystem=NO
