name: Swift

on: 
  push: 


jobs:
  build:
    runs-on: macOS-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,iOS=13.1,name=iPhone11']

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: | 
        pod deintegrate
        xcrun simctl delete all
        xcrun simctl create iPhone11 com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-1
        pod install
        xcodebuild clean test -workspace sdk-ble-swift.xcworkspace -scheme sdk-ble-swift -destination "${destination}"
