name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: pre_build
      run: swift -continue-building-after-errors
    - name: Build 
      run: swift build -v 
