name: Build

on: 
  push: 


jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      env: 
        podfile: $GITHUB_WORKSPACE/Podfile
      run: ./scripts/build.sh
