name: Build

on: 
  push: 


jobs:
  build:
    runs-on: macos-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,OS=latest,name=iPhone11']

    steps:
    - uses: actions/checkout@v2
    - name: set up pod
      run: |
        gem install cocoapods --pr
        pod repo update
    - name: clear and prep
      run: | 
          pod deintegrate
    - name: build
      env: 
        destination: ${{ matrix.destination }}
        podfile: $GITHUB_WORKSPACE/Podfile
      run: ./scripts/build.sh
