name: Build

on: 
  push: 


jobs:
  build:
    runs-on: macos-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,OS=latest,name=iPhone11']

    steps:
    - uses: actions/checkout@v2
    - name: set up pod
      run: |
        gem install cocoapods --pr
        pod repo update
    - name: clear and prep
      run: | 
          pod deintegrate
    - name: build
      env: 
        destination: ${{ matrix.destination }}
      run: | 
        xcrun simctl create iPhone11 com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-2
        pod install
        pod update
        xcodebuild clean -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS"
        xcodebuild build -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS"
