name: CI Build

on: [push]

jobs:
  build: 

    runs-on: macOS-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Build
        run: |
          xcode-select -s /Applications/Xcode_10.2.1.app/Contents/Developer
          pod install
          pod update
          xcodebuild clean -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS"
          xcodebuild build -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS"
