name: Release and Publish

on: 
  push:
    branches:
      - 'master'

jobs: 
  publish:

    runs-on: macOS-latest 

    steps:
      - uses: actions/checkout@v2
      - name: publish to cocoapod register
        run: |
          pod trunk register arie.trouw@xyo.network 'XYO Team' --description='Deploy Script'
          pod lib lint
          pod --allow-warnings trunk push XyBleSdk.podspec